version: '3'

services:
  oghma:
    container_name: oghma
    build:
      context: .
    image: oghma:latest
    restart: unless-stopped
    environment:
      TZ: "Europe/London"
    volumes:
      - /home/<your-username>/oghma:/bot # Replace placeholder
  